@startuml

box "Main process" #LightBlue
	participant Hook_StartActivity
	participant VirtualCore
	participant VActivityManager
end box

box "Server process" #LightGreen
	participant VActivityManagerService
	participant VPackageManagerService
	participant ProviderCaller

end box

box "App Client process" #Gray
	participant StubContentProvider
end box

[-> Hook_StartActivity : onHook

activate Hook_StartActivity
Hook_StartActivity -> VirtualCore : resolveActivityInfo
activate VirtualCore

deactivate VirtualCore

Hook_StartActivity -> VRedirectActRequest : new VRedirectActRequest

activate VRedirectActRequest
Hook_StartActivity <-- VRedirectActRequest : req
deactivate VRedirectActRequest

Hook_StartActivity -> VActivityManager : redirectTargetActivity
activate VActivityManager
    VActivityManager -> VActivityManagerService : redirectTargetActivity
    activate VActivityManagerService
        VActivityManagerService -> VActivityManagerService : redirectTargetActivityLocked
        activate VActivityManagerService
            VActivityManagerService -> VActivityManagerService : startProcessLocked
            activate VActivityManagerService
                VActivityManagerService -> VActivityManagerService : queryFreeStubForProcess
                activate VActivityManagerService
                deactivate VActivityManagerService

                VActivityManagerService -> VActivityManagerService : performStartProcessLocked
                activate VActivityManagerService
                    VActivityManagerService -> VPackageManagerService : querySharedPackages
                    VActivityManagerService <-- VPackageManagerService : sharedPackages : List<String>

                    VActivityManagerService -> VPackageManagerService : queryContentProviders
                    VActivityManagerService <-- VPackageManagerService : providers : List<ProviderInfo>

                    VActivityManagerService -> VPackageManagerService : getSharedLibraries
                    VActivityManagerService <-- VPackageManagerService : usesLibraries : List<String>

                    VActivityManagerService -> ProviderCaller : call(MethodConstants.INIT_PROCESS)
                    activate ProviderCaller
                        ProviderCaller -> StubContentProvider : call
                        activate StubContentProvider
                            StubContentProvider -> StubContentProvider : initProcess
                            activate StubContentProvider
                            deactivate StubContentProvider
                        deactivate StubContentProvider
                        note over ProviderCaller
                            StubContentProvider.java中定义了20个静态内部类C1到C20，都
                            是StubContentProvider的子类。并且在AndroidManifest.xml
                            中声明了process字段，与对应的StubActivity一致。
                            VA的服务进程取出一个空的stubContentProvider，
                            借助Android ContentProvider机制，系统会创建一个新进程出来，
                            稍后被作为双开应用的容身之所。这个偷梁换柱的过程由VA服务进程
                            完成。
                        endnote
                    deactivate ProviderCaller
                deactivate VActivityManagerService
            deactivate VActivityManagerService

            VActivityManagerService -> VActivityManagerService : fetchStubActivityInfo
            activate VActivityManagerService
            deactivate VActivityManagerService

            VActivityManagerService <-- VActRedirectResult : result = new VActRedirectResult
        deactivate VActivityManagerService
    deactivate VActivityManagerService
deactivate VActivityManager

deactivate Hook_StartActivity

@enduml