@startuml
ApplicationThreadNative <|-- ApplicationThread
Binder <|-- ApplicationThreadNative
interface IApplicationThread <|-- ApplicationThreadNative
interface IBinder <|-- Binder
interface IInterface <|-- IApplicationThread
@enduml